Repository prgrms-be-devcourse/NBE3-4-2-Team4, pull requests merged in 2025-02, with the labels that each got.

#8 Feat question(scrum 86)
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/question/controller/QuestionController.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/question/dto/QuestionDto.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/question/dto/request/QuestionWriteReqDto.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/question/dto/response/QuestionWriteResDto.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/question/entity/Question.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/question/entity/QuestionCategory.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/question/initData/QuestionInitData.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/question/repository/QuestionCategoryRepository.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/question/repository/QuestionRepository.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/question/service/QuestionService.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/exceptions/QuestionNotFoundException.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/globalExceptionHandler/GlobalExceptionHandler.java
  backend/src/test/java/com/NBE3_4_2_Team4/domain/board/question/controller/QuestionControllerTest.java
Labels: 개발, 수정

#10 Feat product(scrum 70)
  backend/src/main/java/com/NBE3_4_2_Team4/domain/product/category/repository/ProductCategoryRepository.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/product/product/controller/ProductController.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/product/product/dto/ProductResponseDto.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/product/product/repository/ProductRepository.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/product/product/service/ProductService.java
  backend/src/test/java/com/NBE3_4_2_Team4/domain/product/product/controller/ProductControllerTest.java
Labels: 개발

#12 Feat answer crud(scrum 46)
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/answer/controller/AllAnswerController.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/answer/controller/AnswerController.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/answer/dto/AnswerDto.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/answer/dto/AnswerRequestDto.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/answer/entity/Answer.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/answer/initData/AnswerInitData.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/answer/repository/AnswerRepository.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/answer/service/AnswerService.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/question/controller/QuestionController.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/question/initData/QuestionInitData.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/member/member/initData/MemberInitData.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/aspect/ResponseAspect.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/exceptions/ServiceException.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/globalExceptionHandler/GlobalExceptionHandler.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/rsData/RsData.java
  backend/src/test/java/com/NBE3_4_2_Team4/domain/board/answer/controller/AllAnswerControllerTest.java
  backend/src/test/java/com/NBE3_4_2_Team4/domain/board/answer/controller/AnswerControllerTest.java
  frontend/src/lib/backend/apiV1/schema.d.ts
Labels: 개발

#11 Feat member(scrum 1)
  backend/src/main/java/com/NBE3_4_2_Team4/domain/member/dto/request/LoginRequestDto.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/member/dto/request/SignUpRequestDto.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/member/member/controller/MemberController.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/member/member/entity/Member.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/member/member/initData/MemberInitData.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/member/member/service/MemberService.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/config/OAuth2LogoutFactoryConfig.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/exceptions/InValidAccessException.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/globalExceptionHandler/GlobalExceptionHandler.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/security/oauth2/CustomOAuth2RequestResolver.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/security/oauth2/CustomOAuth2UserService.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/security/oauth2/logout/service/OAuth2LogoutService.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/security/oauth2/logout/service/impl/DefaultLogoutService.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/security/oauth2/logout/service/impl/KakaoLogoutService.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/security/oauth2/userInfo/OAuth2UserInfo.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/security/oauth2/userInfo/OAuth2UserInfoFactory.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/security/oauth2/userInfo/impl/GoogleUserInfo.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/security/oauth2/userInfo/impl/KakaoUserInfo.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/security/oauth2/userInfo/impl/NaverUserInfo.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/security/user/CustomUser.java
  backend/src/main/java/com/NBE3_4_2_Team4/standard/util/Ut.java
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application.yml
  backend/src/test/java/com/NBE3_4_2_Team4/domain/member/member/controller/MemberControllerTest.java
  backend/src/test/java/com/NBE3_4_2_Team4/global/security/filter/CustomJwtFilterTest.java
Labels: 개발

#13 Feat question(scrum 19)
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/question/controller/QuestionController.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/question/entity/Question.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/question/repository/QuestionRepository.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/question/service/QuestionService.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/recommend/controller/RecommendController.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/recommend/entity/Recommend.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/recommend/repository/RecommendRepository.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/recommend/service/RecommendService.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/exceptions/RecommendAlreadyException.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/globalExceptionHandler/GlobalExceptionHandler.java
Labels: 개발

#14 Feat product(scrum 72)
  backend/src/main/java/com/NBE3_4_2_Team4/domain/product/category/entity/ProductCategory.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/product/product/controller/ProductController.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/product/product/initData/ProductInitData.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/product/product/repository/ProductRepository.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/product/product/service/ProductService.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/product/saleState/entity/ProductSaleState.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/product/saleState/entity/SaleState.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/product/saleState/repository/ProductSaleStateRepository.java
  backend/src/test/java/com/NBE3_4_2_Team4/domain/product/product/controller/ProductControllerTest.java
Labels: 개발, 버그, 수정

#15 Feat point(scrum 32)
  .DS_Store
  backend/src/main/java/com/NBE3_4_2_Team4/domain/point/controller/AdminPointController.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/point/controller/PointController.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/point/dto/PointHistoryReq.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/point/dto/PointHistoryRes.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/point/entity/PointCategory.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/point/repository/PointHistoryRepository.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/point/service/PointHistoryService.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/point/service/PointService.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/point/validation/annotation/ValidPointHistoryReq.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/point/validation/validator/PointHistoryReqValidator.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/exceptions/MemberNotFoundException.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/exceptions/PointClientException.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/globalExceptionHandler/GlobalExceptionHandler.java
  backend/src/main/java/com/NBE3_4_2_Team4/standard/util/test/ConcurrencyTestUtil.java
  backend/src/test/java/com/NBE3_4_2_Team4/domain/point/service/PointConcurrencyTest.java
  backend/src/test/java/com/NBE3_4_2_Team4/domain/point/service/PointServiceTest.java
Labels: 개발

#16 Feat point(scrum 32)
  backend/src/main/java/com/NBE3_4_2_Team4/domain/member/member/entity/Member.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/member/member/repository/MemberRepository.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/member/member/service/MemberService.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/point/controller/PointAdminController.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/point/controller/PointController.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/point/dto/PointTransferReq.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/point/entity/PointCategory.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/point/repository/PointHistoryRepository.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/point/service/PointService.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/security/AuthManager.java
  backend/src/main/java/com/NBE3_4_2_Team4/standard/constants/PointConstants.java
  backend/src/test/java/com/NBE3_4_2_Team4/domain/point/.DS_Store
  backend/src/test/java/com/NBE3_4_2_Team4/domain/point/service/PointServiceTest.java
Labels: 개발

#17 Feat front(scrum 103)
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/answer/initData/AnswerInitData.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/question/controller/QuestionController.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/question/dto/QuestionDto.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/question/entity/Question.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/question/initData/QuestionInitData.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/question/service/QuestionService.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/recommend/controller/RecommendController.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/recommend/service/RecommendService.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/exceptions/QuestionNotFoundException.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/exceptions/RecommendAlreadyException.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/globalExceptionHandler/GlobalExceptionHandler.java
  backend/src/test/java/com/NBE3_4_2_Team4/domain/board/question/controller/QuestionControllerTest.java
  backend/src/test/java/com/NBE3_4_2_Team4/domain/board/recommend/controller/RecommendControllerTest.java
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/question/list/ClientPage.tsx
  frontend/src/app/question/list/page.tsx
  frontend/src/lib/backend/apiV1/schema.d.ts
Labels: 개발, 수정

#18 Feat product(scrum 73)
  backend/src/main/java/com/NBE3_4_2_Team4/domain/product/category/repository/ProductCategoryRepository.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/product/product/controller/ProductController.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/product/product/dto/ProductRequestDto.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/product/product/dto/ProductResponseDto.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/product/product/entity/Product.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/product/product/initData/ProductInitData.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/product/product/service/ProductService.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/product/saleState/entity/ProductSaleState.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/product/saleState/repository/ProductSaleStateRepository.java
  backend/src/test/java/com/NBE3_4_2_Team4/domain/product/product/controller/ProductControllerTest.java
Labels: 개발, 수정

#19 Feat question(scrum 18)
  backend/build.gradle.kts
  backend/src/main/generated/com/NBE3_4_2_Team4/domain/board/answer/entity/QAnswer.java
  backend/src/main/generated/com/NBE3_4_2_Team4/domain/board/question/entity/QQuestion.java
  backend/src/main/generated/com/NBE3_4_2_Team4/domain/board/question/entity/QQuestionCategory.java
  backend/src/main/generated/com/NBE3_4_2_Team4/domain/board/recommend/entity/QRecommend.java
  backend/src/main/generated/com/NBE3_4_2_Team4/domain/member/member/entity/QMember.java
  backend/src/main/generated/com/NBE3_4_2_Team4/domain/point/entity/QPointHistory.java
  backend/src/main/generated/com/NBE3_4_2_Team4/domain/product/category/entity/QProductCategory.java
  backend/src/main/generated/com/NBE3_4_2_Team4/domain/product/product/entity/QProduct.java
  backend/src/main/generated/com/NBE3_4_2_Team4/domain/product/saleState/entity/QProductSaleState.java
  backend/src/main/generated/com/NBE3_4_2_Team4/global/jpa/entity/QBaseEntity.java
  backend/src/main/generated/com/NBE3_4_2_Team4/global/jpa/entity/QBaseTime.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/answer/controller/AllAnswerController.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/answer/controller/AnswerController.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/answer/dto/AnswerDto.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/answer/entity/Answer.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/answer/initData/AnswerInitData.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/answer/service/AnswerService.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/question/controller/QuestionController.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/question/dto/QuestionDto.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/question/dto/request/QuestionWriteReqDto.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/question/entity/Question.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/question/initData/QuestionInitData.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/question/repository/QuestionRepository.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/question/repository/QuestionRepositoryCustom.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/question/repository/QuestionRepositoryImpl.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/question/service/QuestionService.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/member/member/initData/MemberInitData.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/point/entity/PointCategory.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/jpa/JpaConfig.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/scheduler/QuestionClosedScheduler.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/scheduler/SchedulingConfig.java
  backend/src/main/java/com/NBE3_4_2_Team4/standard/search/QuestionSearchKeywordType.java
  backend/src/test/java/com/NBE3_4_2_Team4/domain/board/answer/controller/AllAnswerControllerTest.java
  backend/src/test/java/com/NBE3_4_2_Team4/domain/board/answer/controller/AnswerControllerTest.java
  backend/src/test/java/com/NBE3_4_2_Team4/domain/board/question/controller/QuestionControllerTest.java
  frontend/src/lib/backend/apiV1/schema.d.ts
Labels: 개발

#20 Feat question(scrum 109)
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/question/controller/QuestionController.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/question/dto/QuestionDto.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/question/initData/QuestionInitData.java
  frontend/src/app/question/[id]/ClientPage.tsx
  frontend/src/app/question/[id]/page.tsx
  frontend/src/app/question/list/ClientPage.tsx
  frontend/src/app/question/list/page.tsx
  frontend/src/app/question/write/ClientPage.tsx
  frontend/src/app/question/write/page.tsx
  frontend/src/lib/backend/apiV1/schema.d.ts
  frontend/src/utils/convertCase.ts
  frontend/src/utils/dateUtils.ts
Labels: 개발

#24 Feat question(scrum 121)
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/question/controller/QuestionController.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/question/dto/QuestionCategoryDto.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/question/entity/Question.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/question/initData/QuestionInitData.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/question/repository/QuestionRepository.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/question/service/QuestionService.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/recommend/controller/RecommendController.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/recommend/service/RecommendService.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/point/entity/PointCategory.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/scheduler/RankingPointsScheduler.java
  backend/src/test/java/com/NBE3_4_2_Team4/domain/board/recommend/controller/RecommendControllerTest.java
  frontend/src/app/question/list/ClientPage.tsx
  frontend/src/app/question/list/page.tsx
  frontend/src/app/question/rank/ClientPage.tsx
  frontend/src/app/question/rank/page.tsx
  frontend/src/app/question/write/ClientPage.tsx
  frontend/src/app/question/write/page.tsx
  frontend/src/lib/backend/apiV1/schema.d.ts
  frontend/src/utils/apiClient.ts
Labels: 개발, 수정

#25 Feat member(scrum 1)
  backend/src/main/java/com/NBE3_4_2_Team4/domain/member/member/controller/MemberController.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/member/member/dto/MemberThumbnailInfoResponseDto.java
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/ClientLayout.tsx
  frontend/src/app/adm/ClientPage.tsx
  frontend/src/app/adm/login/ClientPage.tsx
  frontend/src/app/login/ClientPage.tsx
  frontend/src/app/mypage/ClientPage.tsx
  frontend/src/app/mypage/edit/nickname/ClientPage.tsx
  frontend/src/app/mypage/edit/nickname/page.tsx
  frontend/src/app/mypage/withdrawal/ClientPage.tsx
  frontend/src/app/mypage/withdrawal/page.tsx
  frontend/src/app/test/page.tsx
  frontend/src/context/IdContext.tsx
  frontend/src/context/NicknameContext.tsx
  frontend/src/lib/backend/apiV1/schema.d.ts
  frontend/src/lib/backend/client.ts
  frontend/src/lib/hooks/useRedirect.tsx
Labels: 개발

#26 Feat point(scrum 32)
  backend/src/main/java/com/NBE3_4_2_Team4/domain/point/controller/PointAdminController.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/point/dto/PointHistoryRes.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/point/dto/PointTransferReq.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/point/initData/PointHistoryInitData.java
  frontend/src/app/ClientLayout.tsx
  frontend/src/app/adm/ClientPage.tsx
  frontend/src/app/point/admin/AccumulateForm.tsx
  frontend/src/app/point/admin/DeductForm.tsx
  frontend/src/app/point/admin/page.tsx
  frontend/src/app/point/list/AttendanceButton.tsx
  frontend/src/app/point/list/ClientPage.tsx
  frontend/src/app/point/list/TransferForm.tsx
  frontend/src/app/point/list/page.tsx
Labels: 개발

#27 Feat answer front(scrum 112)
  backend/src/main/generated/com/NBE3_4_2_Team4/domain/board/answer/entity/QAnswer.java
  backend/src/main/generated/com/NBE3_4_2_Team4/domain/board/question/entity/QQuestion.java
  backend/src/main/generated/com/NBE3_4_2_Team4/domain/member/OAuth2RefreshToken/entity/QOAuth2RefreshToken.java
  backend/src/main/generated/com/NBE3_4_2_Team4/domain/member/member/entity/QMember.java
  backend/src/main/generated/com/NBE3_4_2_Team4/domain/product/saleState/entity/QProductSaleState.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/answer/controller/AllAnswerController.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/answer/controller/AnswerController.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/answer/entity/Answer.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/answer/initData/AnswerInitData.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/answer/repository/AnswerRepository.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/answer/service/AnswerService.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/question/dto/QuestionDto.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/question/service/QuestionService.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/config/SecurityConfig.java
  backend/src/test/java/com/NBE3_4_2_Team4/domain/board/answer/controller/AllAnswerControllerTest.java
  backend/src/test/java/com/NBE3_4_2_Team4/domain/board/answer/controller/AnswerControllerTest.java
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/ClientLayout.tsx
  frontend/src/app/question/[id]/@modal/answer/[answerId]/delete/page.tsx
  frontend/src/app/question/[id]/@modal/answer/[answerId]/select/page.tsx
  frontend/src/app/question/[id]/@modal/default.tsx
  frontend/src/app/question/[id]/ClientPage.tsx
  frontend/src/app/question/[id]/answer/[answerId]/modify/ClientPage.tsx
  frontend/src/app/question/[id]/answer/[answerId]/modify/page.tsx
  frontend/src/app/question/[id]/answer/write/ClientPage.tsx
  frontend/src/app/question/[id]/answer/write/page.tsx
  frontend/src/app/question/[id]/default.tsx
  frontend/src/app/question/[id]/layout.tsx
  frontend/src/app/question/[id]/page.tsx
  frontend/src/components/ui/badge.tsx
  frontend/src/components/ui/card.tsx
  frontend/src/components/ui/dialog.tsx
  frontend/src/components/ui/form.tsx
  frontend/src/components/ui/input.tsx
  frontend/src/components/ui/label.tsx
  frontend/src/components/ui/textarea.tsx
  frontend/src/components/ui/toast.tsx
  frontend/src/components/ui/toaster.tsx
  frontend/src/hooks/use-toast.ts
  frontend/src/lib/backend/apiV1/schema.d.ts
  frontend/src/lib/backend/client.ts
Labels: 개발

#28 Feat product front(scrum 119)
  frontend/next.config.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/adm/ClientPage.tsx
  frontend/src/app/adm/products/edit/[product_id]/ClientPage.tsx
  frontend/src/app/adm/products/edit/[product_id]/page.tsx
  frontend/src/app/adm/products/list/ClientPage.tsx
  frontend/src/app/adm/products/list/page.tsx
  frontend/src/app/adm/products/new/ClientPage.tsx
  frontend/src/app/adm/products/new/page.tsx
  frontend/src/app/shop/[product_id]/ClientPage.tsx
  frontend/src/app/shop/[product_id]/page.tsx
  frontend/src/app/shop/list/ClientPage.tsx
  frontend/src/app/shop/list/page.tsx
  frontend/src/components/ui/pagination.tsx
  frontend/src/components/ui/select.tsx
  frontend/src/components/ui/table.tsx
  frontend/src/lib/backend/apiV1/schema.d.ts
  frontend/src/lib/business/components/PaginationType1.tsx
  frontend/src/lib/business/components/PaginationType1Responsive.tsx
  frontend/src/lib/business/components/product/ProductDetail.tsx
  frontend/src/lib/business/components/product/ProductList.tsx
Labels: 개발

#29 Feat member(scrum 1)
  backend/src/main/java/com/NBE3_4_2_Team4/domain/member/member/controller/MemberController.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/member/member/dto/MemberThumbnailInfoResponseDto.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/security/HttpManager.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/security/filter/CustomJwtFilter.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/security/jwt/JwtManager.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/security/oauth2/disconectService/impl/GoogleDisconnectService.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/security/oauth2/disconectService/impl/KaKaoDisconnectService.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/security/oauth2/disconectService/impl/NaverDisconnectService.java
  backend/src/test/java/com/NBE3_4_2_Team4/domain/member/member/service/MemberServiceTest.java
  backend/src/test/java/com/NBE3_4_2_Team4/global/security/filter/CustomJwtFilterTest.java
  backend/src/test/java/com/NBE3_4_2_Team4/global/security/oAuth2/OAuth2ManagerTest.java
  frontend/package-lock.json
  frontend/src/app/ClientLayout.tsx
  frontend/src/app/adm/ClientPage.tsx
  frontend/src/app/mypage/withdrawal/ClientPage.tsx
  frontend/src/app/test/page.tsx
  frontend/src/context/RoleContext.tsx
  frontend/src/lib/backend/apiV1/schema.d.ts
  frontend/src/lib/backend/client.ts
  frontend/src/lib/hooks/useRedirect.tsx
Labels: 개발

#30 포인트 어드민 인가추가
  frontend/src/app/adm/ClientPage.tsx
  frontend/src/app/adm/point/AccumulateForm.tsx
  frontend/src/app/adm/point/DeductForm.tsx
  frontend/src/app/adm/point/page.tsx
Labels: 개발

#32 Feat member(scrum 1)
  backend/src/main/java/com/NBE3_4_2_Team4/domain/member/member/dto/MemberDetailInfoResponseDto.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/member/member/repository/MemberQuerydsl.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/member/member/service/MemberService.java
  backend/src/test/java/com/NBE3_4_2_Team4/Nbe342Team4ApplicationTests.java
  backend/src/test/java/com/NBE3_4_2_Team4/domain/board/question/controller/QuestionControllerTest.java
  backend/src/test/java/com/NBE3_4_2_Team4/domain/member/member/service/MemberServiceTest.java
  backend/src/test/java/com/NBE3_4_2_Team4/global/security/jwt/JwtManagerTest.java
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/mypage/ClientPage.tsx
  frontend/src/app/mypage/withdrawal/ClientPage.tsx
  frontend/src/lib/backend/apiV1/schema.d.ts
Labels: 개발

#33 Feat question(scrum 125)
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/question/controller/QuestionController.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/question/service/QuestionService.java
  backend/src/test/java/com/NBE3_4_2_Team4/domain/board/question/controller/QuestionControllerTest.java
  frontend/src/app/question/[id]/ClientPage.tsx
  frontend/src/app/question/[id]/edit/ClientPage.tsx
  frontend/src/app/question/[id]/edit/page.tsx
  frontend/src/app/question/list/ClientPage.tsx
  frontend/src/app/question/write/ClientPage.tsx
  frontend/src/lib/backend/apiV1/schema.d.ts
Labels: 수정

#34 Fix product(scrum 128)
  backend/src/main/java/com/NBE3_4_2_Team4/domain/point/service/PointService.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/product/order/controller/ProductOrderController.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/product/order/dto/ProductOrderRequestDto.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/product/order/entity/ProductOrder.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/product/order/repository/ProductOrderRepository.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/product/order/service/ProductOrderService.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/product/product/controller/ProductController.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/product/product/dto/ProductRequestDto.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/product/product/entity/Product.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/product/product/initData/ProductInitData.java
  frontend/next.config.ts
  frontend/src/app/shop/[product_id]/ClientPage.tsx
  frontend/src/app/shop/[product_id]/page.tsx
  frontend/src/app/shop/list/ClientPage.tsx
  frontend/src/app/shop/list/ProductList.tsx
  frontend/src/app/shop/list/page.tsx
  frontend/src/lib/backend/apiV1/schema.d.ts
  frontend/src/lib/business/components/product/ProductDetail.tsx
  frontend/src/utils/imageLoader.ts
Labels: 버그, 수정

#35 Refactor style(scrum 129)
  backend/src/main/generated/com/NBE3_4_2_Team4/domain/product/order/entity/QProductOrder.java
  backend/src/main/generated/com/NBE3_4_2_Team4/domain/product/product/entity/QProduct.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/question/controller/QuestionController.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/question/initData/QuestionInitData.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/question/repository/QuestionRepository.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/question/service/QuestionService.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/product/product/initData/ProductInitData.java
  backend/src/test/java/com/NBE3_4_2_Team4/domain/board/question/controller/QuestionControllerTest.java
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/ClientLayout.tsx
  frontend/src/app/ClientPage.tsx
  frontend/src/app/adm/login/ClientPage.tsx
  frontend/src/app/adm/page.tsx
  frontend/src/app/adm/point/AccumulateForm.tsx
  frontend/src/app/adm/point/DeductForm.tsx
  frontend/src/app/adm/point/page.tsx
  frontend/src/app/adm/products/edit/[product_id]/ClientPage.tsx
  frontend/src/app/adm/products/list/ClientPage.tsx
  frontend/src/app/adm/products/new/ClientPage.tsx
  frontend/src/app/login/ClientPage.tsx
  frontend/src/app/mypage/ClientPage.tsx
  frontend/src/app/mypage/edit/nickname/ClientPage.tsx
  frontend/src/app/mypage/withdrawal/ClientPage.tsx
  frontend/src/app/page.tsx
  frontend/src/app/point/list/AttendanceButton.tsx
  frontend/src/app/point/list/ClientPage.tsx
  frontend/src/app/point/list/TransferForm.tsx
  frontend/src/app/question/[id]/@modal/answer/[answerId]/delete/page.tsx
  frontend/src/app/question/[id]/@modal/delete/page.tsx
  frontend/src/app/question/[id]/ClientPage.tsx
  frontend/src/app/question/[id]/edit/ClientPage.tsx
  frontend/src/app/question/[id]/edit/page.tsx
  frontend/src/app/question/list/ClientPage.tsx
  frontend/src/app/question/list/page.tsx
  frontend/src/app/question/write/ClientPage.tsx
  frontend/src/app/question/write/page.tsx
  frontend/src/app/shop/[product_id]/ClientPage.tsx
  frontend/src/app/shop/list/ClientPage.tsx
  frontend/src/app/shop/list/ProductList.tsx
  frontend/src/app/shop/list/page.tsx
  frontend/src/components/ui/select.tsx
  frontend/src/lib/backend/apiV1/schema.d.ts
  frontend/src/lib/business/components/Pagination1.tsx
  frontend/src/lib/business/components/Pagination2.tsx
Labels: 개발, 수정

#36 Fix product(scrum 130)
  backend/src/main/java/com/NBE3_4_2_Team4/domain/product/order/controller/ProductOrderController.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/product/order/dto/ProductOrderRequestDto.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/product/product/controller/ProductController.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/product/product/initData/ProductInitData.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/product/product/repository/ProductRepository.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/product/product/repository/ProductRepositoryCustom.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/product/product/repository/ProductRepositoryImpl.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/product/product/service/ProductService.java
  backend/src/main/java/com/NBE3_4_2_Team4/standard/search/ProductSearchKeywordType.java
  backend/src/test/java/com/NBE3_4_2_Team4/domain/product/order/controller/ProductOrderControllerTest.java
  backend/src/test/java/com/NBE3_4_2_Team4/domain/product/product/controller/ProductControllerTest.java
  frontend/src/app/shop/list/ClientPage.tsx
  frontend/src/app/shop/list/ProductList.tsx
  frontend/src/app/shop/list/page.tsx
  frontend/src/lib/backend/apiV1/schema.d.ts
Labels: 개발, 버그, 수정

#38 Feat auto attendance point(scrum 141)
  backend/src/main/java/com/NBE3_4_2_Team4/domain/member/OAuth2RefreshToken/entity/OAuth2RefreshToken.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/member/OAuth2RefreshToken/service/OAuth2RefreshTokenService.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/member/member/entity/Member.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/member/member/initData/MemberInitData.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/member/member/repository/MemberQuerydsl.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/member/member/service/MemberService.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/point/entity/PointCategory.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/point/entity/PointHistory.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/point/initData/PointHistoryInitData.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/security/oauth2/CustomOAuth2SuccessHandler.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/security/oauth2/CustomOAuth2UserService.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/security/oauth2/disconectService/OAuth2DisconnectService.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/security/oauth2/disconectService/impl/GoogleDisconnectService.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/security/oauth2/disconectService/impl/KaKaoDisconnectService.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/security/oauth2/disconectService/impl/NaverDisconnectService.java
  backend/src/test/java/com/NBE3_4_2_Team4/domain/member/member/service/MemberServiceTest.java
  frontend/src/app/ClientLayout.tsx
  frontend/src/lib/backend/apiV1/schema.d.ts
Labels: 개발

#39 Feat question(scrum 149)
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/answer/initData/AnswerInitData.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/answer/service/AnswerService.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/question/controller/QuestionCategoryController.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/question/controller/QuestionController.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/question/dto/request/QuestionCategoryReqDto.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/question/entity/Question.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/question/entity/QuestionCategory.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/question/initData/QuestionInitData.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/question/repository/QuestionRepository.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/question/service/QuestionCategoryService.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/question/service/QuestionService.java
  backend/src/test/java/com/NBE3_4_2_Team4/domain/board/question/controller/QuestionControllerTest.java
  frontend/src/app/question/[id]/ClientPage.tsx
  frontend/src/app/shop/list/ProductList.tsx
  frontend/src/lib/backend/apiV1/schema.d.ts
Labels: 개발

#40 Feat product(scrum 145)
  backend/src/main/java/com/NBE3_4_2_Team4/domain/product/order/controller/ProductOrderController.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/product/product/controller/ProductController.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/product/product/initData/ProductInitData.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/product/product/repository/ProductRepositoryCustom.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/product/product/repository/ProductRepositoryImpl.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/product/product/service/ProductService.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/product/saleState/entity/SaleState.java
  backend/src/test/java/com/NBE3_4_2_Team4/domain/product/product/controller/ProductControllerTest.java
  frontend/src/app/adm/products/edit/[product_id]/ClientPage.tsx
  frontend/src/app/adm/products/list/ClientPage.tsx
  frontend/src/app/adm/products/list/page.tsx
  frontend/src/app/adm/products/new/ClientPage.tsx
  frontend/src/app/shop/[product_id]/ClientPage.tsx
  frontend/src/app/shop/list/ClientPage.tsx
  frontend/src/app/shop/list/ProductList.tsx
  frontend/src/app/shop/list/page.tsx
  frontend/src/lib/backend/apiV1/schema.d.ts
  frontend/src/lib/business/components/PaginationType1.tsx
Labels: 개발, 버그, 수정

#42 Feat sign up with additional info(scrum 139)
  backend/build.gradle.kts
  backend/src/main/java/com/NBE3_4_2_Team4/domain/member/member/controller/MemberController.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/member/member/dto/SignupRequestDto.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/member/member/entity/Member.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/member/member/service/MemberService.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/product/product/initData/ProductInitData.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/config/RedisConfig.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/security/AuthManager.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/security/HttpManager.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/security/jwt/JwtManager.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/security/oauth2/CustomOAuth2SuccessHandler.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/security/oauth2/CustomOAuth2UserService.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/security/oauth2/disconectService/scheduler/OAuth2AutoDisconnectScheduler.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/security/oauth2/userInfo/OAuth2UserInfo.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/security/oauth2/userInfo/service/impl/GoogleUserInfoService.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/security/oauth2/userInfo/service/impl/KakaoUserInfoService.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/security/oauth2/userInfo/service/impl/NaverUserInfoService.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/security/user/customUser/CustomUser.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/security/user/customUser/CustomUserDetailService.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/security/user/tempUserBeforeSignUp/TempUserBeforeSignUp.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/security/user/tempUserBeforeSignUp/TempUserBeforeSignUpService.java
  backend/src/main/java/com/NBE3_4_2_Team4/standard/constants/AuthConstants.java
  backend/src/main/resources/application.yml
  backend/src/test/java/com/NBE3_4_2_Team4/domain/asset/cash/CashServiceTest.java
  backend/src/test/java/com/NBE3_4_2_Team4/domain/asset/point/service/PointConcurrencyTest.java
  backend/src/test/java/com/NBE3_4_2_Team4/domain/asset/point/service/PointServiceTest.java
  backend/src/test/java/com/NBE3_4_2_Team4/domain/board/question/controller/QuestionControllerTest.java
  backend/src/test/java/com/NBE3_4_2_Team4/domain/member/member/service/MemberServiceTest.java
  backend/src/test/java/com/NBE3_4_2_Team4/domain/product/product/controller/ProductControllerTest.java
  backend/src/test/java/com/NBE3_4_2_Team4/global/security/filter/CustomJwtFilterTest.java
  backend/src/test/java/com/NBE3_4_2_Team4/global/security/user/tempUserBeforeSignUp/TempUserBeforeSignUpServiceTest.java
  frontend/src/app/ClientLayout.tsx
  frontend/src/app/signup/ClientPage.tsx
  frontend/src/app/signup/page.tsx
  frontend/src/lib/backend/apiV1/schema.d.ts
Labels: 개발

#43 Feat question(scrum 150)
  backend/src/main/java/com/NBE3_4_2_Team4/domain/asset/main/entity/AssetType.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/answer/initData/AnswerInitData.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/question/controller/QuestionController.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/question/dto/QuestionDto.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/question/dto/request/MyQuestionReqDto.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/question/dto/request/QuestionWriteReqDto.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/question/entity/Question.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/question/initData/QuestionInitData.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/question/repository/QuestionRepository.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/question/service/QuestionService.java
  backend/src/main/resources/application.yml
  backend/src/test/java/com/NBE3_4_2_Team4/domain/board/question/controller/QuestionControllerTest.java
  backend/src/test/java/com/NBE3_4_2_Team4/domain/board/recommend/controller/RecommendControllerTest.java
  backend/src/test/java/com/NBE3_4_2_Team4/global/security/filter/CustomJwtFilterTest.java
  frontend/src/app/ClientLayout.tsx
  frontend/src/app/adm/question/ClientPage.tsx
  frontend/src/app/adm/question/page.tsx
  frontend/src/app/mypage/ClientPage.tsx
  frontend/src/app/mypage/posts/ClientPage.tsx
  frontend/src/app/mypage/posts/page.tsx
  frontend/src/app/question/[id]/ClientPage.tsx
  frontend/src/app/question/[id]/edit/ClientPage.tsx
  frontend/src/app/question/list/ClientPage.tsx
  frontend/src/app/question/list/page.tsx
  frontend/src/app/question/write/ClientPage.tsx
  frontend/src/lib/backend/apiV1/schema.d.ts
  frontend/src/lib/business/components/Pagination2.tsx
Labels: 개발

#44 Feat: asset controller
  backend/src/main/java/com/NBE3_4_2_Team4/domain/asset/cash/service/CashService.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/asset/factory/AssetServiceFactory.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/asset/main/controller/AssetAdminController.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/asset/main/controller/AssetController.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/asset/main/dto/AssetHistoryReq.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/asset/main/dto/AssetHistoryRes.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/asset/main/dto/AssetTransferReq.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/asset/main/entity/AssetHistory.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/asset/main/entity/AssetType.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/asset/main/repository/AssetHistoryRepository.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/asset/main/service/AssetHistoryService.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/asset/main/service/AssetService.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/asset/point/controller/PointController.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/asset/point/service/PointService.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/asset/point/validation/validator/PointHistoryReqValidator.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/member/member/dto/MemberDetailInfoResponseDto.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/member/member/repository/MemberQuerydsl.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/security/oauth2/CustomOAuth2SuccessHandler.java
  backend/src/test/java/com/NBE3_4_2_Team4/domain/asset/BaseAssetTestSetup.java
  backend/src/test/java/com/NBE3_4_2_Team4/domain/asset/main/factory/AssetServiceFactoryTest.java
  backend/src/test/java/com/NBE3_4_2_Team4/domain/asset/main/service/AssetServiceTest.java
  backend/src/test/java/com/NBE3_4_2_Team4/domain/asset/point/service/PointServiceTest.java
  frontend/src/app/adm/point/AccumulateForm.tsx
  frontend/src/app/adm/point/DeductForm.tsx
  frontend/src/app/adm/point/page.tsx
  frontend/src/app/mypage/ClientPage.tsx
  frontend/src/app/point/list/ClientPage.tsx
  frontend/src/app/point/list/TransferForm.tsx
  frontend/src/app/point/list/page.tsx
Labels: 개발, 수정

#45 Feat email authentication(scrum 138)
  backend/build.gradle.kts
  backend/src/main/java/com/NBE3_4_2_Team4/domain/asset/point/service/PointService.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/member/member/controller/MemberController.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/member/member/dto/MemberDetailInfoResponseDto.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/member/member/entity/Member.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/member/member/initData/MemberInitData.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/member/member/repository/MemberQuerydsl.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/member/member/service/MemberService.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/config/AsyncConfig.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/config/MailConfig.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/config/SecurityConfig.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/config/WebConfig.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/exceptions/EmailAlreadyVerifiedException.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/mail/service/MailService.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/scheduler/OAuth2AutoDisconnectScheduler.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/security/AuthManager.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/security/jwt/JwtManager.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/security/jwt/JwtObjectMapper.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/security/oauth2/CustomOAuth2SuccessHandler.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/security/oauth2/CustomOAuth2UserService.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/security/user/tempUserBeforeSignUp/TempUserBeforeSignUp.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/security/user/tempUserBeforeSignUp/TempUserBeforeSignUpService.java
  backend/src/main/java/com/NBE3_4_2_Team4/standard/constants/AuthConstants.java
  backend/src/main/resources/application.yml
  backend/src/main/resources/templates/auth-email.html
  backend/src/test/java/com/NBE3_4_2_Team4/domain/member/member/service/MemberServiceTest.java
  backend/src/test/java/com/NBE3_4_2_Team4/global/security/filter/CustomJwtFilterTest.java
  backend/src/test/java/com/NBE3_4_2_Team4/global/security/jwt/JwtManagerTest.java
  backend/src/test/java/com/NBE3_4_2_Team4/global/security/jwt/JwtObjectMapperTest.java
  frontend/src/app/mypage/ClientPage.tsx
  frontend/src/app/mypage/withdrawal/ClientPage.tsx
  frontend/src/app/signup/ClientPage.tsx
  frontend/src/app/signup/complete/ClientPage.tsx
  frontend/src/app/signup/complete/page.tsx
  frontend/src/app/verify-email/already-verified/ClientPage.tsx
  frontend/src/app/verify-email/already-verified/page.tsx
  frontend/src/app/verify-email/fail/ClientPage.tsx
  frontend/src/app/verify-email/fail/page.tsx
  frontend/src/app/verify-email/success/ClientPage.tsx
  frontend/src/app/verify-email/success/page.tsx
  frontend/src/lib/backend/apiV1/schema.d.ts
Labels: 개발
