Repository prgrms-be-devcourse/NBE3-4-2-Team4, pull requests merged in 2025-03, with the labels that each got.

#48 Feat admin asset category
  backend/src/main/java/com/NBE3_4_2_Team4/Nbe342Team4Application.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/asset/cash/entity/CashHistory.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/asset/cash/service/CashService.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/asset/main/controller/AdminAssetCategoryController.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/asset/main/controller/AssetAdminController.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/asset/main/dto/AdminAssetCategoryCreateReq.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/asset/main/dto/AdminAssetCategoryRes.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/asset/main/dto/AdminAssetCategoryUpdateReq.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/asset/main/dto/AdminAssetTransferReq.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/asset/main/dto/AssetHistoryReq.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/asset/main/dto/AssetHistoryRes.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/asset/main/entity/AdminAssetCategory.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/asset/main/entity/AssetHistory.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/asset/main/initData/AdminAssetCategoryInitData.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/asset/main/repository/AdminAssetCategoryRepository.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/asset/main/service/AdminAssetCategoryService.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/asset/main/service/AssetHistoryService.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/asset/main/service/AssetService.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/asset/main/validation/annotation/ValidAssetHistoryReq.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/asset/main/validation/validator/AssetHistoryReqValidator.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/asset/point/controller/PointAdminController.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/asset/point/controller/PointController.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/asset/point/dto/AssetHistoryReq.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/asset/point/dto/AssetHistoryRes.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/asset/point/dto/PointTransferReq.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/asset/point/initData/PointHistoryInitData.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/asset/point/service/PointService.java
  backend/src/test/java/com/NBE3_4_2_Team4/domain/asset/BaseAssetTestSetup.java
  backend/src/test/java/com/NBE3_4_2_Team4/domain/asset/cash/CashServiceTest.java
  backend/src/test/java/com/NBE3_4_2_Team4/domain/asset/main/controller/AdminAssetCategoryControllerTest.java
  backend/src/test/java/com/NBE3_4_2_Team4/domain/asset/main/service/AdminAssetCategoryServiceTest.java
  backend/src/test/java/com/NBE3_4_2_Team4/domain/asset/main/service/AssetServiceTest.java
  backend/src/test/java/com/NBE3_4_2_Team4/domain/asset/point/service/PointServiceTest.java
  backend/src/test/java/com/NBE3_4_2_Team4/global/security/filter/CustomJwtFilterTest.java
  frontend/src/app/adm/point/AccumulateForm.tsx
  frontend/src/app/adm/point/ClientPage.tsx
  frontend/src/app/adm/point/DeductForm.tsx
  frontend/src/app/adm/point/categories/ClientPage.tsx
  frontend/src/app/adm/point/categories/page.tsx
  frontend/src/app/adm/point/page.tsx
  frontend/src/app/point/list/ClientPage.tsx
  frontend/src/app/point/list/TransferForm.tsx
  frontend/src/app/point/list/page.tsx
Labels: 개발

#49 Refactor kotlin answer(scrum 164)
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/answer/controller/AllAnswerController.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/answer/controller/AllAnswerController.kt
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/answer/controller/AnswerController.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/answer/controller/AnswerController.kt
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/answer/dto/AnswerDto.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/answer/dto/AnswerDto.kt
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/answer/dto/AnswerRequestDto.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/answer/dto/AnswerRequestDto.kt
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/answer/entity/Answer.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/answer/entity/Answer.kt
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/answer/initData/AnswerInitData.kt
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/answer/repository/AnswerRepository.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/answer/repository/AnswerRepository.kt
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/answer/service/AnswerService.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/answer/service/AnswerService.kt
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/question/entity/Question.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/question/repository/QuestionRepositoryImpl.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/question/service/QuestionService.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/member/member/entity/Member.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/jpa/entity/BaseEntity.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/jpa/entity/BaseTime.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/rsData/RsData.java
  backend/src/test/java/com/NBE3_4_2_Team4/domain/board/answer/controller/AllAnswerControllerTest.java
  backend/src/test/java/com/NBE3_4_2_Team4/domain/board/answer/controller/AnswerControllerTest.java
Labels: 수정

#50 Feat message(scrum 162)
  .gitignore
  backend/src/main/java/com/NBE3_4_2_Team4/domain/asset/main/entity/AssetCategory.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/message/controller/MessageController.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/message/dto/MessageDto.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/message/dto/request/MessageWriteReqDto.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/message/entity/Message.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/message/entity/MessageType.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/message/initData/MessageInitData.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/message/repository/MessageRepository.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/message/service/MessageService.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/question/controller/QuestionController.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/question/service/QuestionService.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/member/member/repository/MemberRepository.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/config/SecurityConfig.java
  backend/src/test/java/com/NBE3_4_2_Team4/domain/board/message/controller/MessageControllerTest.java
  frontend/src/app/ClientLayout.tsx
  frontend/src/app/message/ClientPage.tsx
  frontend/src/app/message/page.tsx
  frontend/src/app/message/write/ClientPage.tsx
  frontend/src/app/message/write/page.tsx
  frontend/src/app/question/[id]/ClientPage.tsx
  frontend/src/components/icon/message-icon.tsx
  frontend/src/components/ui/red-dot-circle.tsx
  frontend/src/lib/backend/apiV1/schema.d.ts
Labels: 개발, 수정

#51 Refactor kotlin gen file(scrum 166)
  backend/src/main/java/com/NBE3_4_2_Team4/domain/base/genFile/controller/ApiGenFileController.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/base/genFile/controller/ApiGenFileController.kt
  backend/src/main/java/com/NBE3_4_2_Team4/domain/base/genFile/controller/GenFileController.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/base/genFile/controller/GenFileController.kt
  backend/src/main/java/com/NBE3_4_2_Team4/domain/base/genFile/dto/GenFileDto.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/base/genFile/dto/GenFileDto.kt
  backend/src/main/java/com/NBE3_4_2_Team4/domain/base/genFile/entity/GenFile.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/base/genFile/entity/GenFile.kt
  backend/src/main/java/com/NBE3_4_2_Team4/domain/base/genFile/entity/GenFileParent.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/base/genFile/entity/GenFileParent.kt
  backend/src/main/java/com/NBE3_4_2_Team4/domain/base/genFile/initData/GenFileInitData.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/base/genFile/initData/GenFileInitData.kt
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/answer/dto/AnswerDto.kt
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/answer/entity/Answer.kt
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/genFile/controller/AnswerGenFileController.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/genFile/controller/AnswerGenFileController.kt
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/genFile/controller/ApiAnswerGenFileController.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/genFile/controller/ApiAnswerGenFileController.kt
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/genFile/controller/ApiQuestionGenFileController.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/genFile/controller/ApiQuestionGenFileController.kt
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/genFile/controller/QuestionGenFileController.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/genFile/controller/QuestionGenFileController.kt
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/genFile/entity/AnswerGenFile.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/genFile/entity/AnswerGenFile.kt
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/genFile/entity/QuestionGenFile.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/genFile/entity/QuestionGenFile.kt
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/question/entity/Question.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/question/repository/QuestionRepositoryImpl.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/product/genFile/controller/ApiProductGenFileController.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/product/genFile/controller/ApiProductGenFileController.kt
  backend/src/main/java/com/NBE3_4_2_Team4/domain/product/genFile/controller/ProductGenFileController.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/product/genFile/controller/ProductGenFileController.kt
  backend/src/main/java/com/NBE3_4_2_Team4/domain/product/genFile/entity/ProductGenFile.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/product/genFile/entity/ProductGenFile.kt
  backend/src/main/java/com/NBE3_4_2_Team4/domain/product/product/entity/Product.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/config/AppConfig.java
  frontend/src/lib/backend/apiV1/schema.d.ts
Labels: 수정

#54 Feat product payment(scrum 153)
  backend/src/main/java/com/NBE3_4_2_Team4/domain/asset/main/controller/AssetController.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/asset/main/dto/AssetDepositReq.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/asset/main/dto/AssetRefundReq.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/asset/main/entity/AssetCategory.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/asset/point/controller/PointController.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/asset/point/service/PointService.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/member/bankAccount/controller/BankAccountController.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/member/bankAccount/dto/BankAccountRequestDto.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/member/bankAccount/dto/BankAccountResponseDto.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/member/bankAccount/entity/BankAccount.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/member/bankAccount/initData/BankAccountInitData.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/member/bankAccount/repository/BankAccountRepository.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/member/bankAccount/service/BankAccountService.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/member/member/entity/Member.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/payment/payment/controller/PaymentController.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/payment/payment/dto/PaymentRequestDto.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/payment/payment/dto/PaymentResponseDto.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/payment/payment/entity/Payment.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/payment/payment/entity/PaymentStatus.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/payment/payment/repository/PaymentRepository.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/payment/payment/repository/PaymentRepositoryCustom.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/payment/payment/repository/PaymentRepositoryImpl.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/payment/payment/service/PaymentService.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/api/iamport/v1/IamportService.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/api/iamport/v1/IamportServiceImpl.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/api/iamport/v1/account/IamportAccountRequestDto.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/api/iamport/v1/account/IamportAccountResponseDto.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/api/iamport/v1/account/IamportAccountService.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/api/iamport/v1/account/IamportAccountServiceImpl.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/api/iamport/v1/authentication/IamportAuthenticationService.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/api/iamport/v1/authentication/IamportAuthenticationServiceImpl.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/api/iamport/v1/constants/IamportConstants.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/api/iamport/v1/payment/IamportPaymentRequestDto.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/api/iamport/v1/payment/IamportPaymentResponseDto.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/api/iamport/v1/payment/IamportPaymentService.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/api/iamport/v1/payment/IamportPaymentServiceImpl.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/config/SecurityConfig.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/config/SslConfig.java
  backend/src/main/resources/certs/iamport.jks
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/cash/payment/UseImportPayment.tsx
  frontend/src/app/cash/refund/RefundModal.tsx
  frontend/src/app/cash/topup/CashTopupModal.tsx
  frontend/src/app/point/list/ClientPage.tsx
  frontend/src/app/point/list/PayInfoForm.tsx
  frontend/src/app/point/list/page.tsx
  frontend/src/app/point/withdrawal/BankAccountNicknameEditModal.tsx
  frontend/src/app/point/withdrawal/BankManagementModal.tsx
  frontend/src/app/point/withdrawal/ClientPage.tsx
  frontend/src/app/point/withdrawal/WithdrawRequestModal.tsx
  frontend/src/app/point/withdrawal/page.tsx
  frontend/src/components/ui/checkbox.tsx
Labels: 개발, 버그, 수정

#53 Refactor kotlin standard(scrum 168)
  backend/src/main/java/com/NBE3_4_2_Team4/global/config/AppConfig.java
  backend/src/main/java/com/NBE3_4_2_Team4/standard/base/Empty.java
  backend/src/main/java/com/NBE3_4_2_Team4/standard/base/Empty.kt
  backend/src/main/java/com/NBE3_4_2_Team4/standard/constants/AuthConstants.java
  backend/src/main/java/com/NBE3_4_2_Team4/standard/constants/AuthConstants.kt
  backend/src/main/java/com/NBE3_4_2_Team4/standard/constants/PointConstants.java
  backend/src/main/java/com/NBE3_4_2_Team4/standard/constants/PointConstants.kt
  backend/src/main/java/com/NBE3_4_2_Team4/standard/dto/PageDto.java
  backend/src/main/java/com/NBE3_4_2_Team4/standard/dto/PageDto.kt
  backend/src/main/java/com/NBE3_4_2_Team4/standard/search/ProductSearchKeywordType.java
  backend/src/main/java/com/NBE3_4_2_Team4/standard/search/ProductSearchKeywordType.kt
  backend/src/main/java/com/NBE3_4_2_Team4/standard/search/QuestionSearchKeywordType.java
  backend/src/main/java/com/NBE3_4_2_Team4/standard/search/QuestionSearchKeywordType.kt
  backend/src/main/java/com/NBE3_4_2_Team4/standard/util/Ut.java
  backend/src/main/java/com/NBE3_4_2_Team4/standard/util/Ut.kt
  backend/src/main/java/com/NBE3_4_2_Team4/standard/util/UtilConfig.java
  backend/src/main/java/com/NBE3_4_2_Team4/standard/util/UtilConfig.kt
  backend/src/main/java/com/NBE3_4_2_Team4/standard/util/test/ConcurrencyTestUtil.java
  backend/src/main/java/com/NBE3_4_2_Team4/standard/util/test/ConcurrencyTestUtil.kt
Labels: 수정

#58 Feat product payment(scrum 153)
  backend/src/main/java/com/NBE3_4_2_Team4/domain/asset/main/entity/AssetCategory.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/member/bankAccount/service/BankAccountService.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/payment/payment/controller/PaymentController.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/payment/payment/dto/PaymentRequestDto.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/payment/payment/dto/PaymentResponseDto.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/payment/payment/service/PaymentService.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/payment/paymentCancel/entity/PaymentCancel.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/payment/paymentCancel/repository/PaymentCancelRepository.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/product/order/controller/ProductOrderController.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/product/order/dto/ProductOrderRequestDto.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/product/order/service/ProductOrderService.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/api/iamport/v1/payment/IamportPaymentResponseDto.java
  backend/src/test/java/com/NBE3_4_2_Team4/domain/product/order/controller/ProductOrderControllerTest.java
  frontend/package.json
  frontend/src/app/adm/products/list/ClientPage.tsx
  frontend/src/app/adm/products/list/page.tsx
  frontend/src/app/adm/products/new/ClientPage.tsx
  frontend/src/app/cash/ClientPage.tsx
  frontend/src/app/cash/page.tsx
  frontend/src/app/cash/payment/UseImportPayment.tsx
  frontend/src/app/cash/refund/RefundModal.tsx
  frontend/src/app/cash/topup/CashTopupModal.tsx
  frontend/src/app/point/list/PayInfoForm.tsx
  frontend/src/app/shop/[product_id]/ClientPage.tsx
  frontend/src/app/shop/list/ClientPage.tsx
  frontend/src/app/shop/list/ProductList.tsx
  frontend/src/lib/backend/apiV1/schema.d.ts
Labels: 버그, 수정

#56 Refactor kotlin global(scrum 169)
  backend/src/main/java/com/NBE3_4_2_Team4/domain/base/genFile/entity/GenFile.kt
  backend/src/main/java/com/NBE3_4_2_Team4/domain/product/product/repository/ProductRepositoryImpl.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/aspect/ResponseAspect.kt
  backend/src/main/java/com/NBE3_4_2_Team4/global/config/AppConfig.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/config/AppConfig.kt
  backend/src/main/java/com/NBE3_4_2_Team4/global/config/WebConfig.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/config/WebConfig.kt
  backend/src/main/java/com/NBE3_4_2_Team4/global/exceptions/EmailAlreadyVerifiedException.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/exceptions/EmailAlreadyVerifiedException.kt
  backend/src/main/java/com/NBE3_4_2_Team4/global/exceptions/InValidAccessException.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/exceptions/InValidAccessException.kt
  backend/src/main/java/com/NBE3_4_2_Team4/global/exceptions/InValidPasswordException.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/exceptions/InValidPasswordException.kt
  backend/src/main/java/com/NBE3_4_2_Team4/global/exceptions/MemberNotFoundException.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/exceptions/MemberNotFoundException.kt
  backend/src/main/java/com/NBE3_4_2_Team4/global/exceptions/PointClientException.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/exceptions/PointClientException.kt
  backend/src/main/java/com/NBE3_4_2_Team4/global/exceptions/ServiceException.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/exceptions/ServiceException.kt
  backend/src/main/java/com/NBE3_4_2_Team4/global/globalExceptionHandler/GlobalExceptionHandler.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/globalExceptionHandler/GlobalExceptionHandler.kt
  backend/src/main/java/com/NBE3_4_2_Team4/global/initData/DevInitData.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/initData/DevInitData.kt
  backend/src/main/java/com/NBE3_4_2_Team4/global/jpa/JpaConfig.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/jpa/JpaConfig.kt
  backend/src/main/java/com/NBE3_4_2_Team4/global/jpa/entity/BaseEntity.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/jpa/entity/BaseEntity.kt
  backend/src/main/java/com/NBE3_4_2_Team4/global/jpa/entity/BaseTime.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/jpa/entity/BaseTime.kt
  backend/src/main/java/com/NBE3_4_2_Team4/global/rsData/RsData.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/rsData/RsData.kt
  backend/src/main/java/com/NBE3_4_2_Team4/global/scheduler/OAuth2AutoDisconnectScheduler.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/scheduler/OAuth2AutoDisconnectScheduler.kt
  backend/src/main/java/com/NBE3_4_2_Team4/global/scheduler/QuestionClosedScheduler.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/scheduler/QuestionClosedScheduler.kt
  backend/src/main/java/com/NBE3_4_2_Team4/global/scheduler/RankingPointsScheduler.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/scheduler/RankingPointsScheduler.kt
  backend/src/main/java/com/NBE3_4_2_Team4/global/scheduler/SchedulingConfig.java
  backend/src/main/java/com/NBE3_4_2_Team4/global/scheduler/SchedulingConfig.kt
  backend/src/test/java/com/NBE3_4_2_Team4/domain/board/answer/controller/AllAnswerControllerTest.java
  backend/src/test/java/com/NBE3_4_2_Team4/domain/board/answer/controller/AllAnswerControllerTest.kt
  backend/src/test/java/com/NBE3_4_2_Team4/domain/board/answer/controller/AnswerControllerTest.java
  backend/src/test/java/com/NBE3_4_2_Team4/domain/board/answer/controller/AnswerControllerTest.kt
  backend/src/test/java/com/NBE3_4_2_Team4/domain/board/genFile/controller/AnswerGenFileControllerTest.java
  backend/src/test/java/com/NBE3_4_2_Team4/domain/board/genFile/controller/AnswerGenFileControllerTest.kt
  backend/src/test/java/com/NBE3_4_2_Team4/domain/board/genFile/controller/ApiAnswerGenFileControllerTest.java
  backend/src/test/java/com/NBE3_4_2_Team4/domain/board/genFile/controller/ApiAnswerGenFileControllerTest.kt
  backend/src/test/java/com/NBE3_4_2_Team4/domain/board/genFile/controller/ApiQuestionGenFileControllerTest.java
  backend/src/test/java/com/NBE3_4_2_Team4/domain/board/genFile/controller/ApiQuestionGenFileControllerTest.kt
  backend/src/test/java/com/NBE3_4_2_Team4/domain/board/genFile/controller/QuestionGenFileControllerTest.java
  backend/src/test/java/com/NBE3_4_2_Team4/domain/board/genFile/controller/QuestionGenFileControllerTest.kt
  backend/src/test/java/com/NBE3_4_2_Team4/domain/board/question/controller/QuestionControllerTest.kt
  backend/src/test/java/com/NBE3_4_2_Team4/domain/product/genFile/controller/ApiProductGenFileControllerTest.java
  backend/src/test/java/com/NBE3_4_2_Team4/domain/product/genFile/controller/ApiProductGenFileControllerTest.kt
  backend/src/test/java/com/NBE3_4_2_Team4/domain/product/genFile/controller/ProductGenFileControllerTest.java
  backend/src/test/java/com/NBE3_4_2_Team4/domain/product/genFile/controller/ProductGenFileControllerTest.kt
  frontend/src/lib/backend/apiV1/schema.d.ts
Labels: 수정

#60 Feat newsinfo(scrum 176)
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/message/controller/MessageController.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/message/entity/Message.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/message/initData/MessageInitData.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/message/repository/MessageRepository.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/message/service/MessageService.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/question/dto/QuestionDto.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/question/entity/Question.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/question/service/QuestionService.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/search/entity/NewsSearchResult.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/search/service/NewsSearchService.java
  backend/src/test/java/com/NBE3_4_2_Team4/domain/board/message/controller/MessageControllerTest.java
  frontend/src/app/message/ClientPage.tsx
  frontend/src/app/message/ClientWrapper.tsx
  frontend/src/app/message/page.tsx
  frontend/src/app/question/[id]/ClientPage.tsx
  frontend/src/lib/backend/apiV1/schema.d.ts
Labels: 개발, 수정

#61 Feat chat(scrum 161)
  backend/build.gradle.kts
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/message/dto/MessageDto.kt
  backend/src/main/java/com/NBE3_4_2_Team4/domain/board/question/initData/QuestionInitData.kt
  backend/src/main/java/com/NBE3_4_2_Team4/domain/chat/chat/controller/ChatController.kt
  backend/src/main/java/com/NBE3_4_2_Team4/domain/chat/chat/controller/ChatWebSocketController.kt
  backend/src/main/java/com/NBE3_4_2_Team4/domain/chat/chat/dto/ChatDto.kt
  backend/src/main/java/com/NBE3_4_2_Team4/domain/chat/chat/dto/ChatRequestDto.kt
  backend/src/main/java/com/NBE3_4_2_Team4/domain/chat/chat/entity/Chat.kt
  backend/src/main/java/com/NBE3_4_2_Team4/domain/chat/chat/repository/ChatRepository.kt
  backend/src/main/java/com/NBE3_4_2_Team4/domain/chat/chat/service/ChatService.kt
  backend/src/main/java/com/NBE3_4_2_Team4/domain/chat/chatRoom/controller/ChatRoomController.kt
  backend/src/main/java/com/NBE3_4_2_Team4/domain/chat/chatRoom/dto/ChatRoomDto.kt
  backend/src/main/java/com/NBE3_4_2_Team4/domain/chat/chatRoom/dto/ChatRoomRequstDto.kt
  backend/src/main/java/com/NBE3_4_2_Team4/domain/chat/chatRoom/entity/ChatRoom.kt
  backend/src/main/java/com/NBE3_4_2_Team4/domain/chat/chatRoom/entity/ChatRoomMember.kt
  backend/src/main/java/com/NBE3_4_2_Team4/domain/chat/chatRoom/repository/ChatRoomMemberRepository.kt
  backend/src/main/java/com/NBE3_4_2_Team4/domain/chat/chatRoom/repository/ChatRoomRepsitory.kt
  backend/src/main/java/com/NBE3_4_2_Team4/domain/chat/chatRoom/service/ChatRoomService.kt
  backend/src/main/java/com/NBE3_4_2_Team4/domain/chat/initData/ChatInitData.kt
  backend/src/main/java/com/NBE3_4_2_Team4/domain/sse/controller/NotificationController.kt
  backend/src/main/java/com/NBE3_4_2_Team4/domain/sse/dto/ChatNotification.kt
  backend/src/main/java/com/NBE3_4_2_Team4/domain/sse/dto/RejectNotificationRequest.kt
  backend/src/main/java/com/NBE3_4_2_Team4/domain/sse/service/NotificationService.kt
  backend/src/main/java/com/NBE3_4_2_Team4/global/config/WebSocketConfig.kt
  backend/src/test/java/com/NBE3_4_2_Team4/domain/board/message/controller/MessageControllerTest.kt
  backend/src/test/java/com/NBE3_4_2_Team4/domain/board/question/controller/QuestionControllerTest.kt
  backend/src/test/java/com/NBE3_4_2_Team4/domain/board/recommend/controller/RecommendControllerTest.kt
  backend/src/test/java/com/NBE3_4_2_Team4/domain/chat/chat/controller/ChatControllerTest.kt
  backend/src/test/java/com/NBE3_4_2_Team4/domain/chat/chatRoom/controller/ChatRoomControllerTest.kt
  backend/src/test/java/com/NBE3_4_2_Team4/domain/sse/controller/NotificationControllerTest.kt
  backend/src/test/java/com/NBE3_4_2_Team4/global/config/WebSocketTest.kt
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/ClientLayout.tsx
  frontend/src/app/message/ClientPage.tsx
  frontend/src/app/question/[id]/ClientPage.tsx
  frontend/src/app/signup/ClientPage.tsx
  frontend/src/context/UsernameContext.tsx
  frontend/src/hooks/use-toast.ts
  frontend/src/lib/business/components/AlertDialog.tsx
  frontend/src/lib/business/components/ChatWindow.tsx
  frontend/src/lib/business/components/NameButton.tsx
  frontend/src/lib/business/components/RejectDialog.tsx
  frontend/src/lib/hooks/useSSE.ts
Labels: 개발

#64 Fix product payment(scrum 177)
  backend/src/main/java/com/NBE3_4_2_Team4/domain/asset/main/entity/AssetCategory.java
  backend/src/main/java/com/NBE3_4_2_Team4/domain/payment/payment/service/PaymentService.java
  frontend/src/app/cash/ClientPage.tsx
  frontend/src/app/cash/withdrawal/BankAccountNicknameEditModal.tsx
  frontend/src/app/cash/withdrawal/BankManagementModal.tsx
  frontend/src/app/cash/withdrawal/ClientPage.tsx
  frontend/src/app/cash/withdrawal/WithdrawRequestModal.tsx
  frontend/src/app/cash/withdrawal/page.tsx
  frontend/src/app/mypage/withdrawal/ClientPage.tsx
  frontend/src/lib/backend/apiV1/schema.d.ts
Labels: 버그, 수정
